version: '3.8'
services:
  front:
    container_name: posts_upvotes_web
    image: luizgustavoob/posts-upvotes-front:latest
    ports:
      - "4200:4200"
    depends_on: 
      - api
  api:
    container_name: posts_upvotes_api
    image: luizgustavoob/posts-upvotes-api:latest
    ports:
      - "8080:8080"